name: Automatic Web Deploy
on:
  push:
    branches:
    - main
jobs:
  task:
    runs-on: ubuntu-latest
    steps:
    -
      name: Checkout Repository
      uses: actions/checkout@v2
    -
      name: Setup .NET
      uses: actions/setup-dotnet@v1.8.0
      with:
        dotnet-version: 5.0.x
    -
      name: Publish Website
      run: dotnet publish ./FakerSpotter/FakerSpotter.csproj --configuration Release --output ./output
    - 
      name: Fix BaseURL
      run: |
        sed --in-place 's/<base href="\/"\/>/<base href="\/FakerSpotter\/"\/>/g' ./output/wwwroot/index.html
        sed --in-place 's/<base href="\/" \/>/<base href="\/FakerSpotter\/" \/>/g' ./output/wwwroot/index.html
    - 
      name: Disable Jekyll
      run: touch ./output/wwwroot/.nojekyll
    -
      name: Deploy Website
      uses: JamesIves/github-pages-deploy-action@4.1.4
      with:
        branch: website
        folder: ./output/wwwroot
        single-commit: true