on:
  push:
    branches:
      - main
    paths:
      - FakerSpotter/**
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x
    - name: Publish
      run: |
        dotnet publish ./FakerSpotter/FakerSpotter.csproj --configuration Release --output ./output
        sed --in-place 's/<base href="\/"\/>/<base href="\/FakerSpotter\/"\/>/g' ./output/wwwroot/index.html
        sed --in-place 's/<base href="\/" \/>/<base href="\/FakerSpotter\/" \/>/g' ./output/wwwroot/index.html
        cp ./output/wwwroot/index.html ./output/wwwroot/404.html
        touch ./output/wwwroot/.nojekyll
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@4.2.0
      with:
        branch: website
        folder: ./output/wwwroot
        single-commit: true