name: Live Deployment
run-name: "${{ github.workflow }} #${{ github.run_number }}"
on:
  push:
    paths:
      - src/app/**
  workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: true
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  main:
    name: Build & Deploy
    runs-on: ubuntu-latest
    environment:
      name: GitHub Pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Checkout Branch
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Publish Project
        run: |
          dotnet publish src/app/FakerSpotter.csproj --configuration Release --output build
          sed --in-place 's/base href="\/"/base href="\/FakerSpotter\/"/g' build/wwwroot/index.html
          cp build/wwwroot/index.html build/wwwroot/404.html
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: build/wwwroot
      - id: deployment
        name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v1