name: GitHub Pages
on:
  push:
    paths:
      - src/app/**
  workflow_dispatch:
permissions:
  contents: read
  pages: write
  id-token: write
concurrency:
  group: deployment
  cancel-in-progress: true
jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./src/app
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup .NET
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x
      - name: Setup Pages
        uses: actions/configure-pages@v1
      - name: Publish Project
        run: |
          dotnet publish --configuration Release --output build
          sed --in-place 's/base href="\/"/base href="\/FakerSpotter\/"/g' /build/wwwroot/index.html
          cp ./build/wwwroot/index.html ./build/wwwroot/404.html
      - name: Upload Artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./build/wwwroot
  deploy:
    runs-on: ubuntu-latest
    needs: build
    defaults:
      run:
        working-directory: ./src/app
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy Artifacts
        id: deployment
        uses: actions/deploy-pages@v1